version: "1.0"
services:
  postgres-hacka-hotel:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_DB=hacka-hotel
      - POSTGRES_PASSWORD=fiap
    ports:
      - "5432:5432"