version: "3.9"
services:
  postgres-hacka-hotel:
    container_name: db-hacka-hotel
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_DB=hacka-hotel
      - POSTGRES_PASSWORD=fiap
    ports:
      - "54344:5432"
    networks:
      - msnetwork

networks:
  msnetwork:
    external: true