version: "3.9"
services:
  postgres-hacka-hotel-facility-items:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=optionalServices
      - POSTGRES_PASSWORD=root
    ports:
      - "54333:5432"
    networks:
      - msnetwork

networks:
  msnetwork:
    external: true